### ISSUE TITLE
Imported undefined file

### ISSUE THREAD

**Issue by dharsanav** [sarath-sasikumar/ng-dom-image-capture#1]
In  there is an Event file being imported but the repo has no such file

https://github.com/sarath-sasikumar/angular-dom-image-capture/blob/f3b378ff0de3e7ab3ea69486a2a59d687cd91f78/capture.directive.ts#L4

**Comment by sarath-sasikumar** [comment]
The event file has been updated.

**Comment by sarath-sasikumar** [comment]
@dharsanav this may be reopened if the issue persists. It should have been resolved.
