### ISSUE TITLE
Update ReadMe to indicate what is this captureInclude and captureExclude

### ISSUE THREAD

**Issue by dharsanav** [sarath-sasikumar/ng-dom-image-capture#2]
Update ReadMe to indicate what is a captureInclude and captureExclude element.

https://github.com/sarath-sasikumar/angular-dom-image-capture/blob/f3b378ff0de3e7ab3ea69486a2a59d687cd91f78/capture.directive.ts#L68

and 

https://github.com/sarath-sasikumar/angular-dom-image-capture/blob/f3b378ff0de3e7ab3ea69486a2a59d687cd91f78/capture.directive.ts#L102

**Comment by sarath-sasikumar** [comment]
The ReadMe file has been updated and the description for `captureInclude` and `captureExclude` has been provided.
