### ISSUE TITLE
Migrating to a proper repository structure

### ISSUE THREAD

**Issue by kamalbabu** [sarath-sasikumar/ng-dom-image-capture#3]
@sarath-sasikumar  Good job !!! 

I have some humble suggestions. 
a. Repo could be ng-dom-to-image ,  (Brevity matters!!)
b. It would be ideal if you could migrate to a proper repo structure , including test , samples , distribution etc.

Happy Coding!!

**Comment by sarath-sasikumar** [comment]
@kamalbabu , the initial structure was a mess. It was just testing !! :)

Could you check if the package works now and review whether any unnecessary files are there!
It has been published on npm.

**Comment by kamalbabu** [comment]
@sarath-sasikumar will do

**Comment by sarath-sasikumar** [comment]
Please reopen when you do find anything :)
